remote_theme: pmarsceill/just-the-docs

title: dotSetup
email: support@dotsetup.com
description: dotSetup is a free and open source installer for Windows programs.
github_username:  dotsetup

baseurl: "/dotsetup"
url: "https://dotsetup.github.io"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-7FL2W5MPXY
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-relative-links

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
