//
// This code was generated by "..\buildScripts\AutoGenerateAssemblyInfo.exe".
// Any changes made manually will be lost the next time this code is regenerated.
//

using System.Reflection;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("DotSetup")]
[assembly: AssemblyCopyright("Copyright dotSetup.io Open Source Project")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("38495ed0-68b1-4182-a4a3-a385dd430f22")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Release Number
//      Revision
//
[assembly: AssemblyVersion("1.89.0.7743")]
[assembly: AssemblyFileVersion("1.89.0.7743")]
